version: '3.7'
x-default-opts:
  &default-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '10m'
services:
  laravel:
    image: haakco/haakco-api-dev:latest
    hostname: "laravel.server"
#    command: "/testLoop.sh"
    environment:
      - "APP_ENV=${API_APP_ENV}"
      - "APP_IP_AUTHED_LIST=${API_APP_IP_AUTHED_LIST}"
      - "CRONTAB_ACTIVE=${API_CRONTAB_ACTIVE}"
      - "ENABLE_HORIZON=${API_ENABLE_HORIZON}"
      ## Defaults true !!!
      - "ENABLE_DEBUG=${API_ENABLE_DEBUG}"
      - "GEN_LV_ENV=TRUE"
      - "LV_DO_CACHING=FALSE"
      - "NGINX_SITES=${DNS_DOMAIN}"
      - "PHP_MEMORY_LIMIT=${API_PHP_MEMORY_LIMIT}"
      - "PHP_IDE_CONFIG=serverName=${DNS_DOMAIN}"
      - "PHP_OPCACHE_MEMORY_CONSUMPTION=${API_PHP_OPCACHE_MEMORY_CONSUMPTION}"
      - "PHP_OPCACHE_INTERNED_STRINGS_BUFFER=${API_PHP_OPCACHE_INTERNED_STRINGS_BUFFER}"
      - "PHP_OPCACHE_MAX_ACCELERATED_FILES=${API_PHP_OPCACHE_MAX_ACCELERATED_FILES}"
      - "PHP_OPCACHE_REVALIDATE_PATH=${API_PHP_OPCACHE_REVALIDATE_PATH}"
      - "PHP_OPCACHE_ENABLE_FILE_OVERRIDE=${API_PHP_OPCACHE_ENABLE_FILE_OVERRIDE}"
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=${API_PHP_OPCACHE_VALIDATE_TIMESTAMPS}"
      - "PHP_OPCACHE_REVALIDATE_FREQ=${API_PHP_OPCACHE_REVALIDATE_FREQ}"
      - "PHP_MAX_EXECUTION_TIME=${API_PHP_MAX_EXECUTION_TIME}"
      - "PHP_MAX_INPUT_TIME=${API_PHP_MAX_INPUT_TIME}"
      - "PHP_OPCACHE_PRELOAD_FILE=${API_PHP_OPCACHE_PRELOAD_FILE}"
      - "TZ=${TIME_ZONE}"
      - "LVENV_APM_ACTIVE=${API_APM_ACTIVE}"
      - "LVENV_APM_APPNAME=${API_APM_APPNAME}"
      - "LVENV_APM_ENVIRONMENT=${API_APM_ENVIRONMENT}"
      - "LVENV_APM_APPVERSION=${API_APM_APPVERSION}"
      - "LVENV_APM_SERVERURL=${API_APM_SERVERURL}"
      - "LVENV_APM_SECRETTOKEN=${API_APM_SECRETTOKEN}"
      - "LVENV_APP_DEBUG=${API_APP_DEBUG}"
      - "LVENV_APP_ENV=${API_APP_ENV}"
      - "LVENV_APP_KEY=${API_APP_KEY}"
      - "LVENV_APP_NAME=${API_APP_NAME}"
      - "LVENV_APP_TIMEZONE=${TIME_ZONE}"
      - "LVENV_APP_URL=${API_APP_URL}"
      - "LVENV_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "LVENV_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "LVENV_AWS_DEFAULT_REGION=${AWS_REGION}"
      - "LVENV_AWS_BUCKET=${AWS_BUCKET}"
      - "LVENV_AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}"
      - "LVENV_AWS_URL=${AWS_URL}"
      - "LVENV_BROADCAST_DRIVER=${API_BROADCAST_DRIVER}"
      - "LVENV_PUSHER_APP_ID=${API_BROADCAST_PUSHER_APP_ID}"
      - "LVENV_PUSHER_APP_KEY=${API_BROADCAST_PUSHER_APP_KEY}"
      - "LVENV_PUSHER_APP_SECRET=${API_BROADCAST_PUSHER_APP_SECRET}"
      - "LVENV_PUSHER_APP_CLUSTER=${API_BROADCAST_PUSHER_APP_CLUSTER}"
      - "LVENV_PUSHER_HOST=${API_BROADCAST_PUSHER_HOST}"
      - "LVENV_PUSHER_PORT=${API_BROADCAST_PUSHER_PORT}"
      - "LVENV_CACHE_DRIVER=${API_CACHE_DRIVER}"
      - "LVENV_DB_CONNECTION=${API_DB_CONNECTION}"
      - "LVENV_DB_HOST=${API_DB_WRITE_HOST}"
      - "LVENV_DB_PORT=${API_DB_WRITE_PORT}"
      - "LVENV_DB_WRITE_HOST=${API_DB_WRITE_HOST}"
      - "LVENV_DB_WRITE_PORT=${API_DB_WRITE_PORT}"
      - "LVENV_DB_READ_HOST=${API_DB_READ_HOST}"
      - "LVENV_DB_READ_PORT=${API_DB_READ_PORT}"
      - "LVENV_DB_DATABASE=${API_DB_DATABASE}"
      - "LVENV_DB_USERNAME=${API_DB_USERNAME}"
      - "LVENV_DB_PASSWORD=${API_DB_PASSWORD}"
      - "LVENV_FILESYSTEM_CLOUD=${API_FILESYSTEM_CLOUD}"
      - "LVENV_GAMP_TRACKING_ID=${API_GAMP_TRACKING_ID}"
      - "LVENV_GOOGLE_DRIVE_CLIENT_ID=${GOOGLE_DRIVE_CLIENT_ID}"
      - "LVENV_GOOGLE_DRIVE_CLIENT_SECRET=${GOOGLE_DRIVE_CLIENT_SECRET}"
      - "LVENV_GOOGLE_DRIVE_REFRESH_TOKEN=${GOOGLE_DRIVE_REFRESH_TOKEN}"
      - "LVENV_GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}"
      - "LVENV_GOOGLE_DRIVE_TEAM_DRIVE_ID=${GOOGLE_DRIVE_TEAM_DRIVE_ID}"
      - "LVENV_HAAK_COMPANY_NAME=${API_HAAK_COMPANY_NAME}"
      - "LVENV_HAAK_ADMIN_USER=${API_HAAK_ADMIN_USER}"
      - "LVENV_HAAK_ADMIN_USERNAME=${API_HAAK_ADMIN_USERNAME}"
      - "LVENV_HAAK_ADMIN_EMAIL=${API_HAAK_ADMIN_EMAIL}"
      - "LVENV_HAAK_ADMIN_PASSWORD=${API_HAAK_ADMIN_PASSWORD}"
      - "LVENV_SERVER_ADMIN_EMAIL_NAME=${API_HAAK_SERVER_ADMIN_EMAIL_NAME}"
      - "LVENV_HAAK_SERVER_ADMIN_EMAIL=${API_HAAK_SERVER_ADMIN_EMAIL}"
      - "LVENV_HAAK_REGISTRATION_ENABLED=${API_HAAK_REGISTRATION_ENABLED}"
      - "LVENV_HORIZON_WORKERS=${API_HORIZON_WORKERS}"
      - "LVENV_HORIZON_LONG_RUNNING_WORKERS=${API_HORIZON_LONG_RUNNING_WORKERS}"
      - "LVENV_HORIZON_ROUTE=${API_HORIZON_ROUTE}"
      - "LVENV_LOG_CHANNEL=stack"
      - "LVENV_LOG_SQL_QUERIES=false"
      - "LVENV_MAIL_DRIVER=smtp"
      - "LVENV_MAIL_HOST=${API_MAIL_HOST}"
      - "LVENV_MAIL_PORT=${API_MAIL_PORT}"
      - "LVENV_MAIL_USERNAME=${API_MAIL_USERNAME}"
      - "LVENV_MAIL_PASSWORD=${API_MAIL_PASSWORD}"
      - "LVENV_MAIL_ENCRYPTION=${API_MAIL_ENCRYPTION}"
      - "LVENV_MAIL_FROM_ADDRESS=${API_MAIL_FROM_ADDRESS}"
      - "LVENV_MAIL_FROM_NAME=${API_MAIL_FROM_NAME}"
      - "LVENV_MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}"
      - "LVENV_MINIO_SECRET_KEY=${MINIO_SECRET_KEY}"
      - "LVENV_MINIO_ENDPOINT=${API_MINIO_ENDPOINT}"
      - "LVENV_MINIO_BUCKET=${API_MINIO_BUCKET}"
      - "LVENV_MINIO_DEFAULT_REGION=${API_MINIO_DEFAULT_REGION}"
      - "LVENV_MINIO_USE_PATH_STYLE_ENDPOINT=${API_MINIO_USE_PATH_STYLE_ENDPOINT}"
      - "LVENV_PASSPORT_PERSONAL_ACCESS_CLIENT_ID=${LARAVEL_PASSPORT_PERSONAL_ACCESS_CLIENT_ID}"
      - "LVENV_PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=${LARAVEL_PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET}"
      - "LVENV_PASSPORT_PASSWORD_GRANT_CLIENT_ID=${LARAVEL_PASSPORT_PASSWORD_GRANT_CLIENT_ID}"
      - "LVENV_PASSPORT_PASSWORD_GRANT_CLIENT_SECRET=${LARAVEL_PASSPORT_PASSWORD_GRANT_CLIENT_SECRET}"
      - "LVENV_QUEUE_CONNECTION=${API_QUEUE_CONNECTION}"
      - "LVENV_QUEUE_EXPIRE_SECONDS=${API_QUEUE_EXPIRE_SECONDS}"
      - "LVENV_REDIS_CLIENT=phpredis"
      - "LVENV_REDIS_HOST=${API_REDIS_HOST}"
      - "LVENV_REDIS_PORT=${API_REDIS_PORT}"
      - "LVENV_REDIS_PASSWORD=null"
      - "LVENV_REDIS_DB=${API_REDIS_DB}"
      - "LVENV_REDIS_DB_PREFIX=${API_REDIS_PREFIX}"
      - "LVENV_REDIS_SESSION_DB=${API_REDIS_SESSION_DB}"
      - "LVENV_REDIS_SESSION_PREFIX=${API_REDIS_SESSION_PREFIX}"
      - "LVENV_REDIS_CACHE_DB=${API_REDIS_CACHE_DB}"
      - "LVENV_REDIS_CACHE_PREFIX=${API_REDIS_CACHE_PREFIX}"
      - "LVENV_REDIS_HORIZON_DB=${API_REDIS_HORIZON_DB}"
      - "LVENV_REDIS_HORIZON_PREFIX=${API_REDIS_HORIZON_PREFIX}"
      - "LVENV_REDIS_QUEUE_DB=${API_REDIS_QUEUE_DB}"
      - "LVENV_REDIS_QUEUE_PREFIX=${API_REDIS_QUEUE_PREFIX}"
      - "LVENV_REDIS_BROADCAST_DB=${API_REDIS_BROADCAST_DB}"
      - "LVENV_REDIS_BROADCAST_PREFIX=${API_REDIS_BROADCAST_DB}"
      - "LVENV_RESPONSE_CACHE_ENABLED=${API_RESPONSE_CACHE_ENABLED}"
      - "LVENV_RESPONSE_CACHE_DRIVER=${API_RESPONSE_CACHE_DRIVER}"
      - "LVENV_SESSION_DRIVER=${API_SESSION_DRIVER}"
      - "LVENV_SESSION_CONNECTION=${API_SESSION_CONNECTION}"
      - "LVENV_SESSION_LIFETIME=${API_SESSION_LIFETIME}"
      - "LVENV_SLACK_APP_ID=${API_SLACK_APP_ID}"
      - "LVENV_SLACK_CLIENT_ID=${API_SLACK_CLIENT_ID}"
      - "LVENV_SLACK_SECRET=${API_SLACK_SECRET}"
      - "LVENV_SLACK_OAUTH_ACCESS_TOKEN=${API_SLACK_OAUTH_ACCESS_TOKEN}"
      - "LVENV_SLACK_SIGNING_SECRET=${API_SLACK_SIGNING_SECRET}"
      - "LVENV_SLACK_REDIRECT_URI=${API_SLACK_REDIRECT_URI}"
      - "LVENV_SLACK_TOKEN=${API_SLACK_TOKEN}"
      - "LVENV_SLACK_BOT_USERNAME=${API_SLACK_BOT_USERNAME}"
      - "LVENV_SLACK_HOOK_GENERAL=${API_SLACK_HOOK_GENERAL}"
      - "LVENV_TELESCOPE_PATH=${API_TELESCOPE_PATH}"
      - "LVENV_TELESCOPE_ENABLED=true"
      - "LVENV_TRUSTED_PROXIES=${API_TRUSTED_PROXIES}"
      - "ELK_FILEBEAT_ACTIVE=${ELK_FILEBEAT_ACTIVE}"
      - "ELK_FILEBEAT_SHIPPER_NAME=${ELK_FILEBEAT_SHIPPER_NAME}"
      - "ELK_METRICBEAT_ACTIVE=${ELK_METRICBEAT_ACTIVE}"
      - "ELK_METRICBEAT_SHIPPER_NAME=${ELK_METRICBEAT_SHIPPER_NAME}"
      - "ELK_ENVIROMENT=${ELK_ENVIROMENT}"
      - "ELK_KIBANA_HOST=${ELK_KIBANA_HOST}"
      - "ELK_KIBANA_PROTOCOL=${ELK_KIBANA_PROTOCOL}"
      - "ELK_KIBANA_USERNAME=${ELK_KIBANA_USERNAME}"
      - "ELK_KIBANA_PASSWORD=${ELK_KIBANA_PASSWORD}"
      - "ELK_ELASTIC_HOST=${ELK_ELASTIC_HOST}"
      - "ELK_ELASTIC_PROTOCOL=${ELK_ELASTIC_PROTOCOL}"
      - "ELK_ELASTIC_USERNAME=${ELK_ELASTIC_USERNAME}"
      - "ELK_ELASTIC_PASSWORD=${ELK_ELASTIC_PASSWORD}"
      - "LVENV_ELK_ELASTIC_HOST=${ELK_ELASTIC_HOST}"
      - "LVENV_ELK_ELASTIC_USERNAME=${ELK_ELASTIC_USERNAME}"
      - "LVENV_ELK_ELASTIC_PASSWORD=${ELK_ELASTIC_PASSWORD}"
    labels:
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "com.ouroboros.enable=true"
        - "traefik.enable=true"
        - "traefik.http.routers.laravel.rule=Host(`${DNS_DOMAIN}`) && PathPrefix(`/api/v1`)"
        - "traefik.http.routers.laravel.priority=10000"
        - "traefik.http.routers.laravel.entrypoints=websecure"
        - "traefik.http.services.laravel.loadbalancer.server.port=80"
        - "traefik.http.routers.laravel.tls=true"
        - "traefik.http.routers.laravel.middlewares=laravel-compress"
        - "traefik.http.middlewares.laravel-compress.compress=true"
    volumes:
      - "${VOLUME_LARAVEL_API}:/site/web:delegated"
      - "${VOLUME_LARAVEL_API_ZSH_HISTORY_WEB}:/site/.zsh_history:delegated"
      - "${VOLUME_LARAVEL_API_ZSH_HISTORY_ROOT}:/root/.zsh_history:delegated"
      - "${VOLUME_LARAVEL_API_BASH_HISTORY_WEB}:/site/.bash_history:delegated"
      - "${VOLUME_LARAVEL_API_BASH_HISTORY_ROOT}:/root/.bash_history:delegated"
    networks:
      haakco-net:
        aliases:
          - laravel.server
      traefik-net:
        aliases:
          - laravel.server
networks:
  haakco-net:
    attachable: true
    external: true
    driver: overlay
  traefik-net:
    attachable: true
    external: true
    driver: overlay
