version: '3.7'
x-default-opts:
  &default-opts
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
services:
  laravel:
    image: haakco/haakco-api:latest
    hostname: "laravel.server"
#    command: "/testLoop.sh"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - 'traefik.enable=true'
        - "traefik.http.routers.laravel.rule=Host(`${DNS_DOMAIN}`)"
        #        - "traefik.http.routers.laravel.rule=Host(`laravel.${ADMIN_DOMAIN}`) && PathPrefix(/api`, `/horizon`, `/telescope`, `/vendor`)"
        - "traefik.http.routers.laravel.priority=10000"
        - "traefik.http.routers.laravel.entrypoints=websecure"
        - "traefik.http.services.laravel.loadbalancer.server.port=80"
        - "traefik.http.routers.laravel.tls=true"
    environment:
      - "APP_ENV=${API_APP_ENV}"
      - "CRONTAB_ACTIVE=${API_CRONTAB_ACTIVE}"
      - "ENABLE_HORIZON=${API_ENABLE_HORIZON}"
      ## Defaults true !!!
      - "ENABLE_DEBUG=${API_ENABLE_DEBUG}"
      - 'GEN_LV_ENV=TRUE'
      - 'LV_DO_CACHING=FALSE'
      - "NGINX_SITES=${DNS_DOMAIN}"
      - "PHP_MEMORY_LIMIT=${API_PHP_MEMORY_LIMIT}"
      - "PHP_IDE_CONFIG=serverName=${DNS_DOMAIN}"
      - "PHP_OPCACHE_MEMORY_CONSUMPTION=${API_PHP_OPCACHE_MEMORY_CONSUMPTION}"
      - "PHP_OPCACHE_INTERNED_STRINGS_BUFFER=${API_PHP_OPCACHE_INTERNED_STRINGS_BUFFER}"
      - "PHP_OPCACHE_MAX_ACCELERATED_FILES=${API_PHP_OPCACHE_MAX_ACCELERATED_FILES}"
      - "PHP_OPCACHE_REVALIDATE_PATH=${API_PHP_OPCACHE_REVALIDATE_PATH}"
      - "PHP_OPCACHE_ENABLE_FILE_OVERRIDE=${API_PHP_OPCACHE_ENABLE_FILE_OVERRIDE}"
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=${API_PHP_OPCACHE_VALIDATE_TIMESTAMPS}"
      - "PHP_OPCACHE_REVALIDATE_FREQ=${API_PHP_OPCACHE_REVALIDATE_FREQ}"
      - "PHP_MAX_EXECUTION_TIME=${API_PHP_MAX_EXECUTION_TIME}"
      - "PHP_MAX_INPUT_TIME=${API_PHP_MAX_INPUT_TIME}"
      - 'PHP_OPCACHE_PRELOAD_FILE=${API_PHP_OPCACHE_PRELOAD_FILE}'
      - "TZ=${TIME_ZONE}"
      - "WEBSOCKET_ACTIVE=${API_WEBSOCKET_ACTIVE}"
      - "LVENV_LARAVEL_WEBSOCKET_HOST=${API_LARAVEL_WEBSOCKET_HOST}"
      - "LVENV_LARAVEL_WEBSOCKETS_PORT=${API_LARAVEL_WEBSOCKET_PORT}"
      - "LVENV_LARAVEL_WEBSOCKET_ENABLE_STATISTICS=${API_LARAVEL_WEBSOCKET_ENABLE_STATISTICS}"
      - "LVENV_APP_DEBUG=${API_APP_DEBUG}"
      - "LVENV_APP_ENV=${API_APP_ENV}"
      - "LVENV_APP_KEY=${API_APP_KEY}"
      - "LVENV_APP_NAME=${API_APP_NAME}"
      - "LVENV_APP_TIMEZONE=${TIME_ZONE}"
      - "LVENV_APP_URL=${API_APP_URL}"
      - "LVENV_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "LVENV_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "LVENV_AWS_DEFAULT_REGION=${AWS_REGION}"
      - "LVENV_AWS_BUCKET=${AWS_BUCKET}"
      - "LVENV_AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}"
      - "LVENV_AWS_URL=${AWS_URL}"
      - "LVENV_BROADCAST_DRIVER=${API_BROADCAST_DRIVER}"
      - "LVENV_PUSHER_APP_ID=${API_PUSHER_APP_ID}"
      - "LVENV_PUSHER_APP_KEY=${API_PUSHER_APP_KEY}"
      - "LVENV_PUSHER_APP_SECRET=${API_PUSHER_APP_SECRET}"
      - "LVENV_PUSHER_APP_CLUSTER=${API_PUSHER_APP_CLUSTER}"
      - "LVENV_CACHE_DRIVER=${API_CACHE_DRIVER}"
      - "LVENV_DB_CONNECTION=${API_DB_CONNECTION}"
      - "LVENV_DB_HOST=${API_DB_WRITE_HOST}"
      - "LVENV_DB_PORT=${API_DB_WRITE_PORT}"
      - "LVENV_DB_WRITE_HOST=${API_DB_WRITE_HOST}"
      - "LVENV_DB_WRITE_PORT=${API_DB_WRITE_PORT}"
      - "LVENV_DB_READ_HOST=${API_DB_READ_HOST}"
      - "LVENV_DB_READ_PORT=${API_DB_READ_PORT}"
      - "LVENV_DB_DATABASE=${API_DB_DATABASE}"
      - "LVENV_DB_USERNAME=${API_DB_USERNAME}"
      - "LVENV_DB_PASSWORD=${API_DB_PASSWORD}"
      - "LVENV_FILESYSTEM_CLOUD=${API_FILESYSTEM_CLOUD}"
      - "LVENV_GAMP_TRACKING_ID=${API_GAMP_TRACKING_ID}"
      - "LVENV_GOOGLE_DRIVE_CLIENT_ID=${GOOGLE_DRIVE_CLIENT_ID}"
      - "LVENV_GOOGLE_DRIVE_CLIENT_SECRET=${GOOGLE_DRIVE_CLIENT_SECRET}"
      - "LVENV_GOOGLE_DRIVE_REFRESH_TOKEN=${GOOGLE_DRIVE_REFRESH_TOKEN}"
      - "LVENV_GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}"
      - "LVENV_GOOGLE_DRIVE_TEAM_DRIVE_ID=${GOOGLE_DRIVE_TEAM_DRIVE_ID}"
      - "LVENV_HAAK_COMPANY_NAME=${API_HAAK_COMPANY_NAME}"
      - "LVENV_HAAK_ADMIN_USER=${API_HAAK_ADMIN_USER}"
      - "LVENV_HAAK_ADMIN_USER_NAME=${API_HAAK_ADMIN_USER_NAME}"
      - "LVENV_HAAK_ADMIN_EMAIL=${API_HAAK_ADMIN_EMAIL}"
      - "LVENV_HAAK_ADMIN_PASSWORD=${API_HAAK_ADMIN_PASSWORD}"
      - "LVENV_SERVER_ADMIN_EMAIL_NAME=${API_HAAK_SERVER_ADMIN_EMAIL_NAME}"
      - "LVENV_HAAK_SERVER_ADMIN_EMAIL=${API_HAAK_SERVER_ADMIN_EMAIL}"
      - "LVENV_HORIZON_REDIS_DB=${API_HORIZON_REDIS_DB}"
      - "LVENV_HORIZON_WORKERS=${API_HORIZON_WORKERS}"
      - "LVENV_HORIZON_LONG_RUNNING_WORKERS=${API_HORIZON_LONG_RUNNING_WORKERS}"
      - "LVENV_HORIZON_ROUTE=${API_HORIZON_ROUTE}"
      - 'LVENV_LOG_CHANNEL=stack'
      - 'LVENV_LOG_SQL_QUERIES=false'
      - 'LVENV_MAIL_DRIVER=smtp'
      - "LVENV_MAIL_HOST=${API_MAIL_HOST}"
      - "LVENV_MAIL_PORT=$API_MAIL_PORT}"
      - "LVENV_MAIL_USERNAME=${API_MAIL_USERNAME}"
      - "LVENV_MAIL_PASSWORD=${API_MAIL_PASSWORD}"
      - 'LVENV_MAIL_ENCRYPTION=tls'
      - "LVENV_MAIL_FROM_ADDRESS=${API_MAIL_FROM_ADDRESS}"
      - "LVENV_MAIL_FROM_NAME=${API_MAIL_FROM_NAME}"
      - "LVENV_MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}"
      - "LVENV_MINIO_SECRET_KEY=${MINIO_SECRET_KEY}"
      - "LVENV_MINIO_ENDPOINT=${API_MINIO_ENDPOINT}"
      - "LVENV_MINIO_BUCKET=${API_MINIO_BUCKET}"
      - "LVENV_MINIO_DEFAULT_REGION=${API_MINIO_DEFAULT_REGION}"
      - "LVENV_MINIO_USE_PATH_STYLE_ENDPOINT=${API_MINIO_USE_PATH_STYLE_ENDPOINT}"
      - 'LVENV_OPCACHE_URL=http://127.0.0.1'
      - "LVENV_QUEUE_CONNECTION=${API_QUEUE_CONNECTION}"
      - "LVENV_QUEUE_REDIS_DB=${API_QUEUE_REDIS_DB}"
      - "LVENV_QUEUE_EXPIRE_SECONDS=${API_QUEUE_EXPIRE_SECONDS}"
      - "LVENV_REDIS_HOST=${API_REDIS_HOST}"
      - 'LVENV_REDIS_PASSWORD=null'
      - "LVENV_REDIS_PORT=${API_REDIS_PORT}"
      - "LVENV_RESPONSE_CACHE_ENABLED=${API_RESPONSE_CACHE_ENABLED}"
      - "LVENV_RESPONSE_CACHE_DRIVER=${API_RESPONSE_CACHE_DRIVER}"
      - "LVENV_SESSION_DRIVER=${API_SESSION_DRIVER}"
      - "LVENV_SESSION_CONNECTION=${API_SESSION_CONNECTION}"
      - "LVENV_SESSION_LIFETIME=${API_SESSION_LIFETIME}"
      - "LVENV_SLACK_APP_ID=${API_SLACK_APP_ID}"
      - "LVENV_SLACK_CLIENT_ID=${API_SLACK_CLIENT_ID}"
      - "LVENV_SLACK_SECRET=${API_SLACK_SECRET}"
      - "LVENV_SLACK_OAUTH_ACCESS_TOKEN=${API_SLACK_OAUTH_ACCESS_TOKEN}"
      - "LVENV_SLACK_SIGNING_SECRET=${API_SLACK_SIGNING_SECRET}"
      - "LVENV_SLACK_REDIRECT_URI=${API_SLACK_REDIRECT_URI}"
      - "LVENV_SLACK_TOKEN=${API_SLACK_TOKEN}"
      - "LVENV_SLACK_BOT_USERNAME=${API_SLACK_BOT_USERNAME}"
      - "LVENV_SLACK_HOOK_GENERAL=${API_SLACK_HOOK_GENERAL}"
      - "LVENV_TELESCOPE_PATH=${API_TELESCOPE_PATH}"
      - 'LVENV_TELESCOPE_ENABLED=true'
      - "LVENV_TRUSTED_PROXIES=${API_TRUSTED_PROXIES}"
    volumes:
      - "${VOLUME_LARAVEL_API}:/site/web:delegated"
      - "${VOLUME_LARAVEL_API_ZSH_HISTORY_WEB}:/site/.zsh_history:delegated"
      - "${VOLUME_LARAVEL_API_ZSH_HISTORY_ROOT}:/root/.zsh_history:delegated"
      - "${VOLUME_LARAVEL_API_BASH_HISTORY_WEB}:/site/.bash_history:delegated"
      - "${VOLUME_LARAVEL_API_BASH_HISTORY_ROOT}:/root/.bash_history:delegated"
    ports:
      - '6001:6001'
    networks:
      haakco-net:
        aliases:
          - laravel.server
      traefik-net:
        aliases:
          - laravel.server
networks:
  haakco-net:
    attachable: true
    external: true
    driver: overlay
  traefik-net:
    attachable: true
    external: true
    driver: overlay
